# paths:
#   /api/products:
#     get:
#       summary: Obtiene todos los productos
#       tags:
#         - Products
#       responses:
#         "200":
#           description: Los productos fueron satisfactoriamente obtenidos de la base de datos
#         "500": 
#           description: Error interno del servidor...

paths:
  /api/products:
    get:
      tags:
        - Productos
      summary: Obtiene todos los productos
      description: Retorna todos los productos disponibles.
      responses:
        200:
          description: Los productos fueron obtenidos de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        500:
          description: Error interno del servidor. Query invalida o fallo en la conexion con la DB
  /api/products/create:
    post:
      tags:
        - Productos
      summary: Crear un nuevo producto (solo para usuarios Premium y Administradores)
      description: Crea un nuevo producto, solo para usuarios Premium y Administradores.
      parameters:
        - name: product
          in: body
          description: El producto a crear.
          required: true
          schema:
            $ref: '#components/schemas/Products'
      responses:
        200:
          description: Creado
        default:
          description: Error
    security:
      - Bearer: []
      - Admin: []
      - Premium: []
  /api/products/{id}:
    get:
      tags:
        - Productos
      summary: Obtener un producto por ID
      description: Retorna un producto específico según el ID.
      parameters:
        - name: id
          in: path
          description: ID del producto a obtener.
          required: true
          schema: 
            $type: string
      responses:
        200:
          description: Producto encontrado
        default:
          description: Error
    put:
      tags:
        - Productos
      summary: Actualizar un producto por ID (solo para Administradores)
      description: Actualiza un producto específico según el ID, solo para Administradores.
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto que se solicita
          schema:
            $type: string
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Products'
      responses:
        200:
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        500:
          description: Error interno del servidor
    delete:
      tags:
        - Productos
      summary: Eliminar un producto por ID (solo para Administradores y usuarios premium)
      description: Elimina un producto específico según el ID, solo para Administradores y usuarios premium.
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto que se solicita
          schema:
            $type: string
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Products'
      responses:
        200:
          description: Producto eliminado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        500:
          description: Error interno del servidor
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        thumbnail:
          type: array
        code: 
          type: string
        stock:
          type: number
        category:
          type: string
        status: 
          type: boolean
        owner:
          type: string
      example:
        id: 63bf467e58e1baa835re681f
        title": Beefeater 24
        description": Juniper berries, Japanese sencha tea, Chinese green tea, grapefruit peel, lemon peel, almonds, Seville orange peel, coriander seed, orris root, liquorice root, angelica root, angelica seed
        price: 15000
        category: London, England
        thumbnail: ["https://quirinobebidas.com.ar/wp-content/uploads/2020/06/BEEFEATER-24.jpg"]
        code: 1475284
        stock: 450
        status: true
        owner: 6409eb8251f795f5f24f5900
    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'

